### ISSUE TITLE
bdr_init_copy fails with ERROR:  cannot execute DELETE in a read-only transaction

### ISSUE THREAD

**Issue by ringerc** [2ndQuadrant/bdr#255]
Per [mailing list report from Brett Neumeier](https://groups.google.com/a/2ndquadrant.com/forum/#!topic/bdr-list/2FobJI4lGcY):

```
bdr_init_copy: starting ...
Getting remote server identification ...
Detected 1 BDR database(s) on remote server
Updating BDR configuration on the remote node:
 connectivity_dev: creating replication slot ...
 connectivity_dev: creating node entry for local node ...
Creating restore point on remote node ...
Bringing local node to the restore point ...
Could not update security label: ERROR:  cannot execute DELETE in a read-only transaction
```

**Comment by ringerc** [comment]
I already fixed this in 9.6bdr as part of 510c5dd8a28dd17dc08b94a97cdefeebb3c36d94 but thought it was specific to 9.6 so I didn't backport it.

**Comment by ringerc** [comment]
Fixed in bdr-plugin/next . Please confirm fix and I'll cherry-pick it over to bdr-plugin/REL1_0_STABLE for the next release.

**Comment by bneumeier** [comment]
It still does not work, but it does not work differently than before:

```
bdr_init_copy: starting ...
Getting remote server identification ...
Detected 1 BDR database(s) on remote server
Updating BDR configuration on the remote node:
 connectivity_dev: creating replication slot ...
 connectivity_dev: creating node entry for local node ...
Creating restore point on remote node ...
Bringing local node to the restore point ...
Could not remove existing replication origins: ERROR:  relation "pg_catalog.pg_replication_origin" does not exist
LINE 1: ...g_catalog.pg_replication_origin_drop(roname) FROM pg_catalog...

```
and indeed there is no pg_replication_origin; all I see are pg_replication_identifier, pg_replication_identifier_progress, and pg_replication_slots.

I see in the commit there's a test for PG_VERSION_NUM/100 == 94. Building PostgreSQL itself from the bdr-pg/REL9_4_STABLE branch, I wind up with PG_VERSION_NUM = 90409, so maybe this should be PG_VERSION_NUM/100 == 904 ?

**Comment by bneumeier** [comment]
Confirmed -- with the attached patch, bdr_init_copy works as desired. Thanks so much for your help!

[fix-PG_VERSION_NUM-tests.txt](https://github.com/2ndQuadrant/bdr/files/537091/fix-PG_VERSION_NUM-tests.txt)

**Comment by ringerc** [comment]
Thanks. That was a silly oversight! I'll amend that commit and put it in
the queue for the next stable release.​
